### PR TITLE
Support for MathJax 2.7.1 in a hakish way!

### PR DESCRIPTION
**Pull request by OmarIthawi**
Open edX platform Ficus and beyond is using MathJax 2.7. So we need for the extension to support MathJax 2.7 as well.

The array hack caused the extension to partially break. Checkout [my mathjax-dev post](https://groups.google.com/forum/#!topic/mathjax-dev/cWoTKcwMqmY) for more info.

The issue was introduced by: https://github.com/mathjax/MathJax/pull/1523.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
A non-production release [`v1.1-alpha`](https://github.com/Edraak/arabic-mathjax/releases/tag/v1.1-alpha) have been created to demonstrate the bug.

**Comment by OmarIthawi** [comment]
I've added another hack to solve it. This needs to be fixed but I'm still not sure how, let's make it in a future release.

**Comment by dpvc** [comment]
Sorry for the delay in getting back to you.  Hope this helps anyway.

Here is my recommendation.  You don't want to set `copyEnv = true` because that will allow other things to bleed through to the table that shouldn't be.  Instead, we want to copy the `lang` to the `env` after the array stack item is created.  Ideally, that would be done in the `Init()` call, but because the `env` isn't set up until the array pushed onto the stack (and the `Init()` function doesn't have access to the stack), you can't do it then.  Instead, you have to wait for it to be pushed on the stack.  So my suggestion is overriding the stack's `Push()` function and transfer the `lang` if the pushed time is an array.

The following should do it.

```
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  var STACK = MathJax.InputJax.TeX.Stack;
  var PUSH = STACK.prototype.Push;
  STACK.Augment({
    Push: function (item) {
      var lang = this.env.lang;
      PUSH.apply(this,arguments);
      if (lang && item instanceof STACK.Item.array) {
        this.env.lang = lang;
      }
    }
  });
  var CLEAR = STACK.Item.array.prototype.clearEnv;
  STACK.Item.Augment({
    clearEnv: function () {
      let lang = this.env.lang;
      CLEAR.call(this);
      if (lang) this.env.lang = lang;
    }
  });
});
```

This only copies the `lang` property, so doesn't bleed any other properties like `copyEnv` does.

Hope that helps.

**Comment by OmarIthawi** [comment]
No worries at all @dpvc. Yeah, I know that the I'm doing a terrible hack here, but it works for my [basic test suite](edraak.github.io/arabic-mathjax/).

I'll create a test case for the environment bleed 🔪 that I've done. I'll use the code you've suggested to make sure it was fixed, then follow up with another release.

Thanks a lot!

**Pull request merged**
